bremersee:
  access:
    authorities:
      - ROLE_ACTUATOR
    ip-addresses:
      - "127.0.0.1"
      - "::1"
    users:
      - name: actuator
        password: secret4ACTUATOR
        authorities:
          - ROLE_ACTUATOR
  security:
    crypto:
      password-encoder:
        random-salt-length: 16

eureka:
  client:
    enabled: false
    register-with-eureka: true
    prefer-same-zone-eureka: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    health-check-url-path: /actuator/health
    home-page-url-path: /actuator/info
    lease-renewal-interval-in-seconds: 10

logging:
  level:
    ROOT: info
    org.bremersee: debug
    org.springframework: info
#    org.springframework.security.oauth2: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: ${SERVER_PORT:8091}
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: x-forwarded-port

security:
  oauth2:
    client:
      client-id: internal-client
      client-secret: secret4INTERNAL
    resource:
      jwt:
        key-uri: ${OAUTH2_PUBLIC_KEY_URI:http://localhost:8080/oauth/token_key}
      token-info-uri: ${OAUTH2_TOKEN_INFO_URI:http://localhost:8080/oauth/check_token}
      prefer-token-info: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
    property-naming-strategy: LOWER_CAMEL_CASE
    locale: de_DE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: Europe/Berlin
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    enabled: false
    base-url: http://localhost:9411/

---

spring:
  profiles: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:mailcow}?useServerPrepStmts=true&useTimezone=true&useLegacyDatetimeCode=false&serverTimezone=UTC&sendFractionalSeconds=true
    username: ${MYSQL_USER:mailcow}
    password: ${MYSQL_PASSWORD:mailcow}
    platform: mysql
    # HikariCP is the new default connection pool,
    # see: https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html
    # see: https://github.com/brettwooldridge/HikariCP
    #
    hikari:
      pool-name: mailcow
      # If your driver supports JDBC4 we strongly recommend not setting this property.
      # connectionTestQuery: SELECT 1
    # Tomcat pooling DataSource is no longer the default one,
    # see: https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html
    # and: https://tomcat.apache.org/tomcat-8.0-doc/jdbc-pool.html#Common_Attributes
    # Setting test-on-borrow = true is important because connections in the pool can expire and then no longer work.
    # tomcat:
    #   test-on-borrow: true
    #   validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
